export const ADD_EVENT = 'ADD_EVENT';
export const FETCH_CITY_CODE_START = 'FETCH_CITY_CODE_START';
export const FETCH_CITY_CODE_SUCCESS = 'FETCH_CITY_CODE_SUCCESS';
export const FETCH_CITY_CODE_FAIL = 'FETCH_CITY_CODE_FAIL';

export const FETCH_DESCRIPTION_IMAGE_START = 'FETCH_DESCRIPTION_IMAGE_START';
export const FETCH_DESCRIPTION_IMAGE_SUCCESS = 'FETCH_DESCRIPTION_IMAGE_SUCCESS';
export const FETCH_DESCRIPTION_IMAGE_FAIL = 'FETCH_DESCRIPTION_IMAGE_FAIL';

export const FETCH_ACTIVITIES_START = "FETCH_ACTIVITIES_START";
export const FETCH_ACTIVITIES_SUCCESS = "FETCH_ACTIVITIES_SUCCESS";
export const FETCH_ACTIVITIES_FAIL = "FETCH_ACTIVITIES_FAIL";